import React from 'react';
import { AlertTriangle, Info } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface ClinicalDisclaimerProps {
    variant?: 'compact' | 'full';
}

export function ClinicalDisclaimer({ variant = 'full' }: ClinicalDisclaimerProps) {
    if (variant === 'compact') {
        return (
            <div className="flex items-start gap-2 p-3 mt-4 text-xs text-amber-700 bg-amber-50 rounded-md border border-amber-100">
                <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                <p>
                    AI-generated insights may be inaccurate. Always consult a healthcare professional.
                </p>
            </div>
        );
    }

    return (
        <Alert className="mt-6 border-amber-200 bg-amber-50">
            <AlertTriangle className="h-4 w-4 text-amber-600" />
            <AlertTitle className="text-amber-800">Important Medical Disclaimer</AlertTitle>
            <AlertDescription className="text-amber-700 text-sm mt-1">
                These insights are generated by AI based on available data and may not be complete or accurate.
                This information is for educational purposes only and does not constitute medical advice, diagnosis, or treatment.
                Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
            </AlertDescription>
        </Alert>
    );
}
